spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: default
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: false


springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI ?? ??: http://localhost:8080/swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs  # OpenAPI ?? ??

docker:
  workspace-path: /app

liveblocks:
  secret-key: ${LIVEBLOCKS_SECRET_KEY}
  salt: ${LIVEBLOCKS_ROOM_SALT}

template:
  docker-username: ${TEMPLATE_DOCKER_USERNAME}

jwt:
  access:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  refresh:
    secret: ${REFRESH_SECRET}
    expiration: ${REFRESH_EXPIRATION}
