spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: optional:file:.env[.properties]

server:
  port: 8081

# 코드 실행 관련 RabbitMQ 설정
code-execution:
  rabbitmq:
    exchange:
      name: code.execution.exchange
    queue:
      name: code.execution.queue
    routing:
      key: terminal.command.routing-key

# 로그 메시지 전송 관련 RabbitMQ 설정
log:
  rabbitmq:
    exchange:
      name: logs.exchange
    routing:
      key: logs.to.client.key

# RPC for container creation
rpc:
  rabbitmq:
    exchange:
      name: rpc.exchange
    queue:
      name: rpc.container.create.queue
    routing:
      key: rpc.container.create

# 컨테이너 생명주기(삭제) 관련 RabbitMQ 설정
container-lifecycle:
  rabbitmq:
    exchange:
      name: container.lifecycle.exchange
    request: # From Main
      queue-name: container.delete.queue
      routing-key: container.delete.key
    response: # To Main
      routing-key: container.deleted.ack.key

# [신규] PTY 기반 Stateful 터미널 세션 관련 설정
pty-session:
  rabbitmq:
    start: # 세션 시작 요청 수신
      exchange: pty.start.exchange
      queue: pty.start.queue
      routing-key: pty.start.key
    command: # 명령어 수신
      exchange: pty.command.exchange
      queue: pty.command.queue
      routing-key: pty.command.key
