spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000ms
        default-requeue-rejected: false

server:
  port: 8081

# 코드 실행 관련 RabbitMQ 설정
code-execution:
  rabbitmq:
    exchange:
      name: code.execution.exchange
    queue:
      name: code.execution.queue
    routing:
      key: terminal.command.routing-key

# 로그 메시지 전송 관련 RabbitMQ 설정
log:
  rabbitmq:
    exchange:
      name: logs.exchange
    routing:
      key: logs.to.client.key

# RPC for container creation
rpc:
  rabbitmq:
    exchange:
      name: rpc.exchange
    queue:
      name: rpc.container.create.queue
    routing:
      key: rpc.container.create

# 컨테이너 생명주기(삭제) 관련 RabbitMQ 설정
container-lifecycle:
  rabbitmq:
    exchange:
      name: container.lifecycle.exchange
    request: # From Main
      queue-name: container.delete.queue
      routing-key: container.delete.key
    response: # To Main
      routing-key: container.deleted.ack.key

# [신규] PTY 기반 Stateful 터미널 세션 관련 설정
pty-session:
  rabbitmq:
    start: # 세션 시작 요청 수신
      exchange: pty.start.exchange
      queue: pty.start.queue
      routing-key: pty.start.key
    command: # 명령어 수신
      exchange: pty.command.exchange
      queue: pty.command.queue
      routing-key: pty.command.key

# 컨테이너 할당 요청 관련 RabbitMQ 설정
container-acquire:
  rabbitmq:
    exchange:
      name: container.acquire.exchange
    queue:
      name: container.acquire.queue
    routing:
      key: container.acquire.routing-key

# 컨테이너 정리 요청 관련 RabbitMQ 설정
container-cleanup:
  rabbitmq:
    exchange:
      name: container.cleanup.exchange
    queue:
      name: container.cleanup.queue
    routing:
      key: container.cleanup.routing-key

# 컨테이너 관련 작업 응답을 위한 RabbitMQ 설정
container-response:
  rabbitmq:
    exchange:
      name: container.response.exchange
    queue:
      name:
        acquire-success: container.aq.success.queue
        acquire-failure: container.aq.failure.queue
        cleanup-success: container.cleanup.success.queue
    routing:
      key:
        acquire-success: container.acquire.success
        acquire-failure: container.acquire.failure
        cleanup-success: container.cleanup.success

# 프로젝트 삭제 요청 관련 RabbitMQ 설정
project-delete:
  rabbitmq:
    exchange:
      name: project.delete.exchange
    queue:
      name: project.delete.queue
    routing:
      key: project.delete.routing-key

# 프로젝트 관련 작업 응답을 위한 RabbitMQ 설정
project-response:
  rabbitmq:
    exchange:
      name: project.response.exchange
    queue:
      name:
        delete-success: project.delete.success.queue
    routing:
      key:
        delete-success: project.delete.success.routing-key
