spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/${RDS_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&connectTimeout=10000&socketTimeout=10000&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_DB_USER_NAME}
    password: ${RDS_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

docker:
  host:
    # 운영 환경에서는 EC2에 마운트된 EFS 경로를 사용합니다.
    workspace-base-path: /mnt/efs/workspaces
  container:
    workspace-path: /app
