spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: optional:file:.env[.properties]

server:
  port: 8081

# 코드 실행 관련 RabbitMQ 설정
code-execution:
  rabbitmq:
    exchange:
      name: code.execution.exchange
    queue:
      name: code.execution.queue
    routing:
      key: code.execution.routing-key

# 터미널 명령어 관련 RabbitMQ 설정
terminal-command:
  rabbitmq:
    exchange:
      name: terminal.command.exchange
    queue:
      name: terminal.command.queue
    routing:
      key: terminal.command.routing-key

# 로그 메시지 전송 관련 RabbitMQ 설정
log:
  rabbitmq:
    exchange:
      name: logs.exchange
    routing:
      key: logs.to.client.key

# RPC for container creation
rpc:
  rabbitmq:
    exchange:
      name: rpc.exchange
    queue:
      name: rpc.container.create.queue
    routing:
      key: rpc.container.create
